-
  branches:
    only:
      - master
  image: Visual Studio 2017
  environment:
    NuGet: a2NMkYADRjkx04ZF09emp2hncwtVF6MfLvckIlXXVrHvySEduX/NfqVcmio4lI39
  cache: 
    - .tmp
  before_build:
    - ps: gitversion /l console /output buildserver
  build_script:
    - ps: .\build.ps1 -configuration Release -target Compile
  test_script:
    - ps: .\build.ps1 -configuration Release -target Test
  after_test:
    - ps: .\build.ps1 -configuration Release -target Pack
  artifacts:
    - path: 'output\packages\*.nupkg'
- 
  image: Visual Studio 2017
  cache: 
    - .tmp
  before_build:
    - ps: gitversion /l console /output buildserver
  build_script:
    - ps: .\build.ps1 -configuration Release -target Compile
  test_script:
    - ps: .\build.ps1 -configuration Release -target Test
